OTC-878: add permissions to all gql mutations and queries
openimis/openimis-be-self_registration_py pull request #6
Opened 2023-03-15 11:08 UTC by jdolkowski

https://openimis.atlassian.net/browse/OTC-878

2023-03-16 08:16 UTC, dragos-dobre requested changes

2023-03-16 08:16 UTC, dragos-dobre commented on self_registration/gql_mutations.py
>          print(root.length)
Is this for debug? Please remove if not need anymore.

2023-03-16 08:16 UTC, dragos-dobre commented on self_registration/gql_mutations.py
>          print(insuree_obj.pk)
Is this for debug? Please remove if not need anymore.

2023-03-16 08:16 UTC, dragos-dobre commented on self_registration/gql_mutations.py
>          print(kwargs)
Is this for debug? Please remove if not needed anymore.

2023-03-16 08:16 UTC, dragos-dobre commented on self_registration/gql_mutations.py
>          print('CreateNoticeMutation mutate')
Is this for debug? Please remove if not needed anymore.

2023-03-16 08:16 UTC, dragos-dobre commented on self_registration/gql_mutations.py
>          dfprint('UpdateNoticeMutation mutate')
Is this for debug? Please remove if not needed anymore.

2023-03-16 08:16 UTC, dragos-dobre commented on self_registration/gql_mutations.py
>          dfprint(kwargs)
Is this for debug? Please remove if not needed anymore.

2023-03-16 08:16 UTC, dragos-dobre commented on self_registration/gql_mutations.py
>          dfprint('CreateInsureeMutation mutate')
Is this for debug? Please remove if not needed anymore.

2023-03-16 08:16 UTC, dragos-dobre commented on self_registration/schema.py
>          print('asdasd',phone_no)
Is this for debug? Please remove if not needed anymore.

2023-03-16 09:07 UTC, jdolkowski commented
@dragos-dobre I removed all of the prints. I left them because I didn't want to change the code I didn't write, but I guess they do not serve any purpose whatsoever.

2023-03-21 11:34 UTC, delcroip approved these changes

2023-03-21 11:35 UTC, delcroip commented
@dragos-dobre  please merge it when happy with the changes

2023-04-12 12:55 UTC, merged